### ISSUE TITLE
please add license for files from ofxGLEditor

### ISSUE THREAD

**Issue by danomatika** [darrenmothersele/ofxEditor#3]
Howdy,

I see you're using some code from ofxGLEditor, mainly the Clipboard class and it looks like the ofxEditor class is based largely on ofxGLEditor. We (I at least) don't really have a problem with people taking/reusing our code, but at the very least, you need to keep our license header for the Clipboard instead of inserting your own. It would be nice to acknowledge our work if it's been useful ... plus that's a requirement of the GPL v2.

Also, I haven't tried this addon yet, but I've been thinking of rewriting the GLEditor class and it appears you've done it. We should think of a possible merge. Frankly, the fluxus GLEditor is a bit ugly and was funky to get working in OF so something it bit more extensible is welcome.

**Comment by darrenmothersele** [comment]
I've added the MIT license, which is the one that openFrameworks is licensed under. It is compatible with the GPL license that ofxGLEditor is licensed under, so I think this is correct. In fact, as ofxGLEditor is linked with openFrameworks libraries, doesn't this need the MIT license too?

**Comment by danomatika** [comment]
The MIT is a permissive license, you don't need to relicense any code you use with it. 

ofxGLEditor is GPL, however, which means you need license any code that directly uses (compiles/links) it as GPL if you plan to distribute it (aka Github). The reason why we used the GPL is because the Fluxus source is GPL so we had to in order to use the GLEditor class while remaining compliant to the original license. If we rewrote our own version GLEditor and it's support classes, we could then relicense to something more permissive, say MIT or BSD.

Naturally, with so many licenses mixing, it can seem unclear. What bothers me on this case, is that you took some code we wrote for this project (which is fine) but **removed the license and authors from the header** (this is not fine). Again, it can be grey as to whether you keep the license if you heavily modify something but I at least keep an acknowledgement of where I got the basis form. In this case the code was not modified (Clipboard class), so you should have left the header and not replaced it with your own. t may be a strong word, but some would amount that to plagiarism.

Again, this is a small bit of code but I think the spirit of reuse should be honored.

**Comment by darrenmothersele** [comment]
I'm not trying to steal any code here, I thought I'd left comments in that acknowledged where it was adapted from. I'll check, and if they're missing I'll make sure they are added and proper attribution is included.

**Comment by darrenmothersele** [comment]
header re-added - sorry, for some reason XCode had put it's own default header in and I hadn't noticed!

**Comment by danomatika** [comment]
Sure. I'm probably being overly anal in the spirit of OF openness but I hope you see my point. We licensed the files themselves so that license should stay irregardless of acknowledgements/etc in the readme. I'm not a lawyer but from what I've read, that's the best way to ensure covering code and I follow it as a matter of principle.

**Comment by danomatika** [comment]
Yeah, I actually thought it was Xcode ... That's not cool Apple :P
